#!/bin/bash

ln -s ~/dotfiles/.bash_aliases ~/.bash_aliases;
ln -s ~/dotfiles/.bash_extras ~/.bash_extras;
ln -s ~/dotfiles/.bash_profile ~/.bash_profile;
ln -s ~/dotfiles/.bash_setup ~/.bash_setup;
ln -s ~/private-dotfiles/.bash_cc ~/.bash_cc;

ln -s ~/dotfiles/.condarc ~/.condarc;
ln -s ~/dotfiles/.noserc ~/.noserc;
ln -s ~/dotfiles/.sreenrc ~/.screenrc;
ln -s ~/dotfiles/easy_extraction ~/easy_extraction;
ln -s ~/dotfiles/setup.cnf ~/setup.cnf;

