#!/bin/bash

FILES="dotfiles/.bash_aliases
dotfiles/.bash_extras
dotfiles/.bash_profile
dotfiles/.bash_setup
dotfiles/.salling_aliases
dotfiles/.condarc
dotfiles/.screenrc
dotfiles/easy_extraction
dotfiles/setup.cfg
dotfiles/.inputrc"

for file in $FILES;
do
  link="${file/*\//~/}"  # Replace folder name with "~/": ${parameter/pattern/string}
  if [ ! -L $link ]; then
    ln -s $file $link
    echo "Created symlink from $file to $link"
  fi;
done
